#!/bin/bash
echo "════════════════════════════════════════════════════════"
echo "  CHI INSURANCE PORTAL - Management System v1.0"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📊 Dashboard:"
echo "  python manage.py status"
echo ""
echo "📧 Send Renewals:"
echo "  python send_renewals.py --dry-run    # Test"
echo "  python send_renewals.py              # Send"
echo ""
echo "💰 Payments:"
echo "  python manage.py pending"
echo "  python manage.py mark-paid 1234"
echo ""
echo "👥 Clients:"
echo "  python manage.py clients"
echo "  python manage.py add-policy"
echo ""
echo "📄 PDF Import:"
echo "  python src/ocr/pdf_extractor.py data/raw_pdfs/"
echo "  python src/database/import_data.py"
echo ""
echo "Full reference: cat COMMANDS.md"
echo "════════════════════════════════════════════════════════"
echo ""
source venv/bin/activate
