#!/bin/bash

echo "═══════════════════════════════════════════════════════════════"
echo "  CHI INSURANCE BROKER PORTAL"
echo "  Management System v1.0"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📊 Dashboard & Status:"
echo "  python manage.py status          # Payment dashboard"
echo "  python manage.py pending         # Pending payments"
echo "  python manage.py paid            # Paid payments"
echo ""
echo "👥 Client Management:"
echo "  python manage.py clients         # List all clients"
echo "  python manage.py search ΜΑΜΜΗ    # Search client"
echo "  python manage.py edit 4          # Edit client info"
echo ""
echo "💰 Payment Actions:"
echo "  python manage.py mark-paid 1234  # Mark as paid"
echo "  python manage.py add-policy      # Add new policy"
echo ""
echo "📄 PDF Processing:"
echo "  python src/ocr/pdf_extractor.py data/raw_pdfs/  # Extract all"
echo "  python src/database/import_data.py              # Import to DB"
echo ""
echo "📖 Full reference: cat COMMANDS.md"
echo "═══════════════════════════════════════════════════════════════"
echo ""

source venv/bin/activate
